### ISSUE TITLE
Could not find dmm reference point.

### ISSUE THREAD

**Issue by sharvies** [XVs32/kcauto_custom#26]
#### Environment details

* kcauto version (version on first line of `CHANGELOG.md`): #### v8.1.0
* Operating system and/or VM: windows 10

#### Issue variability
Is the issue consistent (can be reproduced consistently) or is it intermittent (only happens sometimes)?:

consistent problem

#### Issue

Please provide a thorough description of the issue. Screenshots, videos, or at least a step-by-step description of what is happening in the game is typically necessary to debug.

kcauto can not recognize kancolle splash screen

#### Log
```
[insert ~50 lines of console log (or more) here; remove section if irrelevant]
```
[2023-04-13 20:58:34] Initializing kcauto.
[2023-04-13 20:58:34] Config successfully loaded.
[2023-04-13 20:58:34] Fleet 1 activated.
[2023-04-13 20:58:34] Quest module enabled.
[2023-04-13 20:58:34] Loading Quest data.
[2023-04-13 20:58:34] Loading Quest priority data.
[2023-04-13 20:58:34] Hooking into Chrome.
[2023-04-13 20:58:47] Connected to Chrome
[2023-04-13 20:58:47] Initializing kcauto vv8.0.0-rc1 in command-line mode with the 'template\basic-factory' config file.
[2023-04-13 20:58:47] Finding DMM.
[2023-04-13 20:58:47] Could not find dmm reference point.
[2023-04-13 20:58:47] FindFailed stacktrace:
Traceback (most recent call last):
  File "kcauto\util\kca.py", line 144, in find_dmm
    screen, f'global|dmm_logo.png')
  File "kcauto\util\kca.py", line 412, in find
    return r.find(self._create_asset_path(asset), similarity, cached)
  File "C:\Users\Admin\.virtualenvs\kcauto_custom-master-KO12a4qv\lib\site-packages\pyvisauto\__init__.py", line 115, in find
    raise FindFailed(f"{target} not found in {self}!")
pyvisauto.FindFailed: assets\global\dmm_logo.png not found in [ X:0, Y:0, W:1366, H:768 ]!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "kcauto\kcauto_wrapper.py", line 22, in kcauto_main
    _.kcauto.find_dmm()
  File "kcauto\kcauto.py", line 37, in find_dmm
    kca_u.kca.find_dmm()
  File "kcauto\util\kca.py", line 147, in find_dmm
    raise FindFailed()
pyvisauto.FindFailed

[2023-04-13 20:58:47] End stacktrace.
[2023-04-13 20:58:47] Attempting recovery.
[2023-04-13 20:58:49] Finding kancolle.
[2023-04-13 20:58:55] Could not find Kancolle reference point.
[2023-04-13 20:58:55] Recovery failed. Shutting down kcauto.

#### Config
```
[insert relevant config sections here; remove section if irrelevant]
```
basic-factory.json in template folder

**Comment by sharvies** [comment]
it works! very thanks.
