### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by kenahamtan** [XVs32/kcauto_custom#54]
#### Environment details

* kcauto version (version on first line of `CHANGELOG.md`): Window V2
* Operating system and/or VM: Win11 64bit

#### Issue variability
Is the issue consistent (can be reproduced consistently) or is it intermittent (only happens sometimes)?: Yes

#### Issue

Migrated from old kcauto_custom build of february 2023 to the current window v2.  Run a expedition script and terminated with UnicodeEncodeError.

#### Log
```
C:\kcauto_custom>python kcauto --cfg exp
←[92m[2023-07-30 18:28:10] Initializing kcauto.←[0m
←[92m[2023-07-30 18:28:10] Config successfully loaded.←[0m
←[92m[2023-07-30 18:28:11] Fleet 1 activated.←[0m
←[94m[2023-07-30 18:28:11] Loading Quest data.←[0m
←[94m[2023-07-30 18:28:11] Loading Quest priority data.←[0m
←[92m[2023-07-30 18:28:11] Expedition module enabled.←[0m
[2023-07-30 18:28:11] Hooking into Chrome.
[2023-07-30 18:28:23] Connected to Chrome
[2023-07-30 18:28:23] Initializing kcauto v2.0.0-beta in command-line mode with the 'exp' config file.
[2023-07-30 18:28:23] Finding browser.
[2023-07-30 18:28:25] Starting kancolle from splash screen.
[2023-07-30 18:28:28] Fleet 2 activated.
[2023-07-30 18:28:28] Fleet 2 is away on assignment.
[2023-07-30 18:28:28] Fleet 2 returns at 2023-07-30 18:33:23.
[2023-07-30 18:28:28] Fleet 3 activated.
[2023-07-30 18:28:28] Fleet 3 is away on assignment.
[2023-07-30 18:28:28] Fleet 3 returns at 2023-07-30 18:43:42.
[2023-07-30 18:28:28] Fleet 4 activated.
[2023-07-30 18:28:28] Fleet 4 is away on assignment.
[2023-07-30 18:28:28] Fleet 4 returns at 2023-07-30 20:58:58.
[2023-07-30 18:28:31] Kancolle successfully started.
[2023-07-30 18:28:32] Finding kancolle.
[2023-07-30 18:28:32] Game found. Initializing regions.
[2023-07-30 18:28:32] kcauto has been running for 0d 0h 0m 21s (loop 1).
[2023-07-30 18:28:32] 0 Expeditions sent (0.00/hr) / 0 Expeditions received (0.00/hr)
[2023-07-30 18:28:32] Fleet 2 / On expedition / Returning at 2023-07-30 18:33:23
[2023-07-30 18:28:32] Fleet 3 / On expedition / Returning at 2023-07-30 18:43:42
[2023-07-30 18:28:32] Fleet 4 / On expedition / Returning at 2023-07-30 20:58:58
[2023-07-30 18:28:32] Fuel:349718 (Δ0 : 0.00/hr) / Ammo:349872 (Δ0 : 0.00/hr) / Steel:350000 (Δ0 : 0.00/hr) / Bauxite:350000 (Δ0 : 0.00/hr) / Bucket:3000 (Δ0 : 0.00/hr)
Traceback (most recent call last):
  File "C:\Users\Milamber\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Milamber\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "kcauto\__main__.py", line 26, in <module>
    kcauto_main()
  File "kcauto\startup\kcauto_wrapper.py", line 43, in kcauto_main
    _.kcauto.print_stats()
  File "kcauto\startup\kcauto.py", line 337, in print_stats
    sts.stats.print_stats()
  File "kcauto\stats\stats_core.py", line 106, in print_stats
    Log.log_success(self.rsc)
  File "kcauto\util\logger.py", line 60, in log_success
    cls.log_file.write(cls._log_format(msg) + "\n")
  File "C:\Users\Milamber\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u0394' in position 35: character maps to <undefined>

C:\kcauto_custom>
```

#### Config
```
[insert relevant config sections here; remove section if irrelevant]
```

**Comment by kenahamtan** [comment]
had tried C:\kcauto_custom>set PYTHONIOENCODING=utf-8
same error

**Comment by kenahamtan** [comment]
I compared to the log file which the code is trying to write the first (position 35) Greek unicode char "delta" and could not..

**Comment by XVs32** [comment]
Hi kenahamtan,

I don't have win 11 here but it seems that the latest version works fine on win 10:
![364639361_670946121295457_275312136411745169_n](https://github.com/XVs32/kcauto_custom/assets/16824564/3dd3bd37-2e3e-491e-93e0-f34f4fe14daa)


The `←[92m` in your log shows that terminal is not handling the color code properly.

```
←[92m[2023-07-30 18:28:10] Initializing kcauto.←[0m
←[92m[2023-07-30 18:28:10] Config successfully loaded.←[0m
←[92m[2023-07-30 18:28:11] Fleet 1 activated.←[0m
←[94m[2023-07-30 18:28:11] Loading Quest data.←[0m
←[94m[2023-07-30 18:28:11] Loading Quest priority data.←[0m
←[92m[2023-07-30 18:28:11] Expedition module enabled.←[0m
```

I am assuming these few lines are not green(`←[92m`) or blue(`←[94m`) in your terminal.

It is strange to me that only the first few lines has the color code on it, 
but anyway, this looks like a terminal/environment problem to me.

Here are somethings that I would want to know/you might want to try:
1. Since you are just updating kcauto_custom, I am assuming that you didn't change your terminal/python at all?
2. It seems that you are using your own python environment, maybe updating the python library could help (`pip install -r requirements.txt`), cause I do import new libraries when needed.
3. Maybe you would want to give the `.exe` a try, just to see if this is a python environment problem, or it is win11's problem.

**Comment by kenahamtan** [comment]
this last part which is writing to log file is the issue and causing the program termination:

[2023-07-30 18:28:32] Fuel:349718 (Δ0 : 0.00/hr) / Ammo:349872 (Δ0 : 0.00/hr) / Steel:350000 (Δ0 : 0.00/hr) / Bauxite:350000 (Δ0 : 0.00/hr) / Bucket:3000 (Δ0 : 0.00/hr)
Traceback (most recent call last):
  File "C:\Users\Milamber\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Milamber\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "kcauto\__main__.py", line 26, in <module>
    kcauto_main()
  File "kcauto\startup\kcauto_wrapper.py", line 43, in kcauto_main
    _.kcauto.print_stats()
  File "kcauto\startup\kcauto.py", line 337, in print_stats
    sts.stats.print_stats()
  **File "kcauto\stats\stats_core.py", line 106, in print_stats
    Log.log_success(self.rsc)
  File "kcauto\util\logger.py", line 60, in log_success
    cls.log_file.write(cls._log_format(msg) + "\n")
  File "C:\Users\Milamber\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u0394' in position 35: character maps to <undefined>**

It is trying to write Δ (unicode) to log file but can't cause logger.py is writing string.

A quick workaround is change the Δ (rsc.py) to a string char (eg +) then it is working fine.

**Comment by XVs32** [comment]
I would want to find out why this is happening, but well...

**Comment by kenahamtan** [comment]
###  Q&A
1. Since you are just updating kcauto_custom, I am assuming that you didn't change your terminal/python at all?  nope

2. It seems that you are using your own python environment, maybe updating the python library could help (pip install -r requirements.txt), cause I do import new libraries when needed.   
Yes I did that when I move to WinV2

3. Maybe you would want to give the .exe a try, just to see if this is a python environment problem, or it is win11's problem.
Yes the .exe give out about the same error, it did not display the full traceback.

###  Resolution
> I would want to find out why this is happening, but well...

This is the final resolution for writing unicode to file.
Edit util\logger.py line  21 to look like this
cls.log_file = open( "log/" + dt_string + ".log", "w", encoding="utf-8")

Reference:
https://stackoverflow.com/questions/52351619/python-3-unicodeencodeerror-charmap-codec-cant-encode-character-encode-so

According to the reference above, the file needs to be opened as UTF-8 encoding for writing unicode into it.

"In your code above you don't specify an encoding when you use open, and in this case Python will use the default encoding for your locale. This varies by system, and it looks like the default locale for your system doesn't support the Greek letter "χ"."

**Comment by XVs32** [comment]
Thank you for the reply.

So somehow your system default is not UTF encoding plus my code relies on UTF.
That's how I couldn't manage to reproduce the problem.

Thanks again for your effort, I will fix this soon.
